add: user controllers
iaurg/42-transcendence pull request #40
Opened 2023-06-10 18:15 UTC by LuigiEnzoFerrari

## Description
Implementation of CRUD to the entity users

## Related Issue
#35

2023-06-10 18:24 UTC, vcwild commented
Maybe create a single userDto, not 2 dtos, add optional decorator on distinct fields between update and create dtos

2023-06-10 18:25 UTC, vcwild requested changes
Create a single userDto entity that reflects the same user model

2023-06-11 04:32 UTC, julianochoi commented on backend/src/users/users.service.ts
The `create` method should have an argument of a DTO equivalent to at least all required fields of the User schema.

2023-06-12 23:05 UTC, julianochoi approved these changes

2023-06-12 23:59 UTC, vcwild approved these changes

2023-06-12 23:59 UTC, merged